version: "3.8"
name: qudis-dev
services:
  postgres:
    image: postgres:16
    command: "-d 1"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main

volumes:
  postgres_data:
