name: Deploy to AWS with Copilot

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install AWS Copilot CLI
      - name: Install AWS Copilot CLI
        uses: ksivamuthu/aws-copilot-github-action@v0.0.8
        with:
          command: install

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::603045522989:role/ecs-deploy
          aws-region: ap-northeast-1

      # Deploy using AWS Copilot
      - name: Deploy to AWS with Copilot
        run: copilot deploy
